#Task2: Try Linear regression on same prediction data using Tensorflow

In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [ ]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [ ]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.61125314, 0.86103858],
       [0.24731417, 0.80780256],
       [0.92013879, 0.70700917]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([ 0.28613097, -0.93170373])>


In [ ]:
def model(s):
    return s @ v + r

In [ ]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[101.04362782 146.4482786 ]
 [136.56269661 193.75801939]
 [139.9733031  223.2307278 ]
 [107.31359607 147.78908105]
 [130.61447363 185.51964606]
 [101.04362782 146.4482786 ]
 [136.56269661 193.75801939]
 [139.9733031  223.2307278 ]
 [107.31359607 147.78908105]
 [130.61447363 185.51964606]
 [101.04362782 146.4482786 ]
 [136.56269661 193.75801939]
 [139.9733031  223.2307278 ]
 [107.31359607 147.78908105]
 [130.61447363 185.51964606]], shape=(15, 2), dtype=float64)


In [ ]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(5288.604742569195, shape=(), dtype=float64)


In [ ]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 5288.604742569195
 
 Epoch count: 1 
 Loss value: 3477.3923686758203
 
 Epoch count: 2 
 Loss value: 2324.034189829162
 
 Epoch count: 3 
 Loss value: 1584.7056974737782
 
 Epoch count: 4 
 Loss value: 1106.567348971904
 
 Epoch count: 5 
 Loss value: 793.7367070388262
 
 Epoch count: 6 
 Loss value: 585.9961744963167
 
 Epoch count: 7 
 Loss value: 445.468627144942
 
 Epoch count: 8 
 Loss value: 348.27822375092995
 
 Epoch count: 9 
 Loss value: 279.3303545155098
 
 Epoch count: 10 
 Loss value: 229.04328880242358
 
 Epoch count: 11 
 Loss value: 191.3011303767338
 
 Epoch count: 12 
 Loss value: 162.17110925232802
 
 Epoch count: 13 
 Loss value: 139.09929522671536
 
 Epoch count: 14 
 Loss value: 120.40583450266512
 
 Epoch count: 15 
 Loss value: 104.96776362507633
 
 Epoch count: 16 
 Loss value: 92.01934375857513
 
 Epoch count: 17 
 Loss value: 81.02606675675972
 
 Epoch count: 18 
 Loss value: 71.60488295856916
 
 Epoch count: 19 
 Loss value: 6